// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0Hhd7EkkiDoRsyUQX_RhZXUuCOaTmoKg',
    appId: '1:147518364258:web:c3e611e74edadc331e8f3b',
    messagingSenderId: '147518364258',
    projectId: 'resto-reco-app',
    authDomain: 'resto-reco-app.firebaseapp.com',
    storageBucket: 'resto-reco-app.firebasestorage.app',
    measurementId: 'G-2TR1LF0VZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsShXJLER6h5dn0ZnCpRfgS9nW0pVFNis',
    appId: '1:147518364258:android:3b413e690240d00e1e8f3b',
    messagingSenderId: '147518364258',
    projectId: 'resto-reco-app',
    storageBucket: 'resto-reco-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFOtgzos2Jmt8FSGA1YLasFtUeLdoK3AY',
    appId: '1:147518364258:ios:72cbff5a60cc9d901e8f3b',
    messagingSenderId: '147518364258',
    projectId: 'resto-reco-app',
    storageBucket: 'resto-reco-app.firebasestorage.app',
    iosBundleId: 'com.example.restorecommendapps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFOtgzos2Jmt8FSGA1YLasFtUeLdoK3AY',
    appId: '1:147518364258:ios:72cbff5a60cc9d901e8f3b',
    messagingSenderId: '147518364258',
    projectId: 'resto-reco-app',
    storageBucket: 'resto-reco-app.firebasestorage.app',
    iosBundleId: 'com.example.restorecommendapps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0Hhd7EkkiDoRsyUQX_RhZXUuCOaTmoKg',
    appId: '1:147518364258:web:a3bdfef0e999ad3a1e8f3b',
    messagingSenderId: '147518364258',
    projectId: 'resto-reco-app',
    authDomain: 'resto-reco-app.firebaseapp.com',
    storageBucket: 'resto-reco-app.firebasestorage.app',
    measurementId: 'G-SCDHPLDJV0',
  );

}